export const AVAILABLES = {
  data: {
    availables: [
      {
        currency: {
          id: "BTC",
          name: "Bitcoin",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.0083506",
        estPrice: "91141.05",
        estValue: "761.08",
      },
      {
        currency: {
          id: "ETH",
          name: "Ethereum",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.04256646",
        estPrice: "3143.105",
        estValue: "133.79",
      },
      {
        currency: {
          id: "USDC",
          name: "USD Coin",
          decimals: 4,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "76.4778",
        estPrice: "1.00065",
        estValue: "76.52",
      },
      {
        currency: {
          id: "SOL",
          name: "Solana",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.29265251",
        estPrice: "135.045",
        estValue: "39.52",
      },
      {
        currency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "34.49",
        estPrice: "1",
        estValue: "34.49",
      },
      {
        currency: {
          id: "LTC",
          name: "Litecoin",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.31385887",
        estPrice: "81.345",
        estValue: "25.53",
      },
      {
        currency: {
          id: "AAVE",
          name: "Aave",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.05343409",
        estPrice: "167.335",
        estValue: "8.94",
      },
      {
        currency: {
          id: "TRX",
          name: "Tron",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "28.5",
        estPrice: "0.298185",
        estValue: "8.49",
      },
      {
        currency: {
          id: "POL",
          name: "Polygon",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "47.1512903",
        estPrice: "0.12655",
        estValue: "5.96",
      },
      {
        currency: {
          id: "AVAX",
          name: "Avalanche",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.40678629",
        estPrice: "14.0275",
        estValue: "5.7",
      },
      {
        currency: {
          id: "ADA",
          name: "Cardano",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "12.220851",
        estPrice: "0.40305",
        estValue: "4.92",
      },
      {
        currency: {
          id: "DOT",
          name: "Polkadot",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "1.78200088",
        estPrice: "2.1505",
        estValue: "3.83",
      },
      {
        currency: {
          id: "CHZ",
          name: "Chiliz",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "86.858",
        estPrice: "0.042765",
        estValue: "3.71",
      },
      {
        currency: {
          id: "MANA",
          name: "Decentraland",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "25.898",
        estPrice: "0.14125",
        estValue: "3.65",
      },
      {
        currency: {
          id: "LINK",
          name: "Chainlink",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.25559",
        estPrice: "13.3735",
        estValue: "3.41",
      },
      {
        currency: {
          id: "DAI",
          name: "Dai",
          decimals: 4,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "3.1135",
        estPrice: "1.00065",
        estValue: "3.11",
      },
      {
        currency: {
          id: "UNI",
          name: "Uniswap",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        estPrice: "5.723",
        estValue: "0",
      },
      {
        currency: {
          id: "XRP",
          name: "Ripple",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0.00000096",
        estPrice: "2.19215",
        estValue: "0",
      },
      {
        currency: {
          id: "SAND",
          name: "Sandbox",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        estPrice: "0.12095",
        estValue: "0",
      },
      {
        currency: {
          id: "S",
          name: "Sonic",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        estPrice: "0.09325",
        estValue: "0",
      },
    ],
    estTotalValue: "1122.65",
  },
  status: 200,
};
