export const CURRENCY = [
  {
    id: "BTC",
    name: "Bitcoin",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 3,
  },
  {
    id: "USDT",
    name: "Tether",
    decimals: 2,
    allowTransfers: true,
    disabled: false,
    priority: 3,
  },
  {
    id: "USDC",
    name: "USD Coin",
    decimals: 4,
    allowTransfers: true,
    disabled: false,
    priority: 2,
  },
  {
    id: "ETH",
    name: "Ethereum",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 2,
  },
  {
    id: "DAI",
    name: "Dai",
    decimals: 4,
    allowTransfers: true,
    disabled: false,
    priority: 2,
  },
  {
    id: "LINK",
    name: "Chainlink",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "UNI",
    name: "Uniswap",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "POL",
    name: "Polygon",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "SOL",
    name: "Solana",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "ADA",
    name: "Cardano",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "XRP",
    name: "Ripple",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "TRX",
    name: "Tron",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "LTC",
    name: "Litecoin",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "DOT",
    name: "Polkadot",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 1,
  },
  {
    id: "CHZ",
    name: "Chiliz",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 0,
  },
  {
    id: "QIA",
    name: "Quantia",
    decimals: 2,
    allowTransfers: false,
    disabled: true,
    priority: 0,
  },
  {
    id: "SAND",
    name: "Sandbox",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 0,
  },
  {
    id: "MANA",
    name: "Decentraland",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 0,
  },
  {
    id: "AAVE",
    name: "Aave",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 0,
  },
  {
    id: "AVAX",
    name: "Avalanche",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 0,
  },
  {
    id: "S",
    name: "Sonic",
    decimals: 8,
    allowTransfers: true,
    disabled: false,
    priority: 0,
  },
];
