import { NetWorthData } from "@/services/hooks/types/net-worth-data";

export const NET_WORTH_DATA: NetWorthData = {
  assets: {
    clientId: "79f970d7-3b2f-492c-a358-6c1f1c2fd429",
    assets: [
      {
        currency: {
          id: "BTC",
          name: "Bitcoin",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.0083506",
        locked: "0.00016514",
        total: "0.00851574",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "94040.55",
        estValue: "800.82",
      },
      {
        currency: {
          id: "ETH",
          name: "Ethereum",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.04256646",
        locked: "0.04683954",
        total: "0.089406",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "3202.515",
        estValue: "286.32",
      },
      {
        currency: {
          id: "USDC",
          name: "USD Coin",
          decimals: 4,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "76.4778",
        locked: "0",
        total: "76.4778",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "1.00015",
        estValue: "76.48",
      },
      {
        currency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "34.49",
        locked: "34.54",
        total: "69.03",
        staking: {
          initial: "33.3",
          accrued: "0.24",
        },
        estPrice: "1",
        estValue: "69.03",
      },
      {
        currency: {
          id: "SOL",
          name: "Solana",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.29265251",
        locked: "0",
        total: "0.29265251",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "135.955",
        estValue: "39.78",
      },
      {
        currency: {
          id: "LTC",
          name: "Litecoin",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.31385887",
        locked: "0",
        total: "0.31385887",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "83.195",
        estValue: "26.11",
      },
      {
        currency: {
          id: "AAVE",
          name: "Aave",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.05343409",
        locked: "0",
        total: "0.05343409",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "172.245",
        estValue: "9.2",
      },
      {
        currency: {
          id: "TRX",
          name: "Tron",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "28.5",
        locked: "0",
        total: "28.5",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.291785",
        estValue: "8.31",
      },
      {
        currency: {
          id: "POL",
          name: "Polygon",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "47.1512903",
        locked: "0",
        total: "47.1512903",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.12435",
        estValue: "5.86",
      },
      {
        currency: {
          id: "AVAX",
          name: "Avalanche",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.40678629",
        locked: "0",
        total: "0.40678629",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "14.2265",
        estValue: "5.78",
      },
      {
        currency: {
          id: "ADA",
          name: "Cardano",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "12.220851",
        locked: "0",
        total: "12.220851",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.41345",
        estValue: "5.05",
      },
      {
        currency: {
          id: "CHZ",
          name: "Chiliz",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "86.858",
        locked: "0",
        total: "86.858",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.045675",
        estValue: "3.96",
      },
      {
        currency: {
          id: "DOT",
          name: "Polkadot",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "1.78200088",
        locked: "0",
        total: "1.78200088",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "2.1985",
        estValue: "3.91",
      },
      {
        currency: {
          id: "MANA",
          name: "Decentraland",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "25.898",
        locked: "0",
        total: "25.898",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.14155",
        estValue: "3.66",
      },
      {
        currency: {
          id: "LINK",
          name: "Chainlink",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.25559",
        locked: "0",
        total: "0.25559",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "13.7515",
        estValue: "3.51",
      },
      {
        currency: {
          id: "DAI",
          name: "Dai",
          decimals: 4,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "3.1135",
        locked: "0",
        total: "3.1135",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "1.00015",
        estValue: "3.11",
      },
      {
        currency: {
          id: "UNI",
          name: "Uniswap",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0",
        locked: "0",
        total: "0",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "5.858",
        estValue: "0",
      },
      {
        currency: {
          id: "XRP",
          name: "Ripple",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0.00000096",
        locked: "0",
        total: "0.00000096",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "2.21435",
        estValue: "0",
      },
      {
        currency: {
          id: "SAND",
          name: "Sandbox",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0",
        locked: "0",
        total: "0",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.12475",
        estValue: "0",
      },
      {
        currency: {
          id: "S",
          name: "Sonic",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        available: "0",
        locked: "0",
        total: "0",
        staking: {
          initial: "0",
          accrued: "0",
        },
        estPrice: "0.094585",
        estValue: "0",
      },
    ],
    estTotalValue: "1350.89",
  },
  liabilities: {
    liabilities: [
      {
        currency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "32.48",
        debt: "32.48",
        interest: "0.36",
        estPrice: "1",
        estValue: "32.48",
        estInterestValue: "0.36",
      },
      {
        currency: {
          id: "BTC",
          name: "Bitcoin",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "94040.55",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "DAI",
          name: "Dai",
          decimals: 4,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "1.00015",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "USDC",
          name: "USD Coin",
          decimals: 4,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "1.00015",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "ETH",
          name: "Ethereum",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 2,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "3202.515",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "LTC",
          name: "Litecoin",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "83.195",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "LINK",
          name: "Chainlink",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "13.7515",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "UNI",
          name: "Uniswap",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "5.858",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "POL",
          name: "Polygon",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.12435",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "ADA",
          name: "Cardano",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.41345",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "SOL",
          name: "Solana",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "135.955",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "XRP",
          name: "Ripple",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "2.21465",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "TRX",
          name: "Tron",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.291785",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "DOT",
          name: "Polkadot",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 1,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "2.1985",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "AVAX",
          name: "Avalanche",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "14.2265",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "CHZ",
          name: "Chiliz",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.045675",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "SAND",
          name: "Sandbox",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.12475",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "MANA",
          name: "Decentraland",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.14155",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "S",
          name: "Sonic",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "0.094585",
        estValue: "0",
        estInterestValue: "0",
      },
      {
        currency: {
          id: "AAVE",
          name: "Aave",
          decimals: 8,
          allowTransfers: true,
          disabled: false,
          priority: 0,
        },
        quoteCurrency: {
          id: "USDT",
          name: "Tether",
          decimals: 2,
          allowTransfers: true,
          disabled: false,
          priority: 3,
        },
        amount: "0",
        debt: "0",
        interest: "0",
        estPrice: "172.225",
        estValue: "0",
        estInterestValue: "0",
      },
    ],
    estTotalValue: "32.48",
    estTotalInterestValue: "0.36",
  },
  estTotalValue: "1318.41",
};
