import { User } from "@/services/hooks/types/user-data";

export const USERS_DATA: User[] = [
  {
    id: "1",
    fullName: "María García Rodríguez",
    avatar: "M",
    email: "maria.garcia@crocante.com",
    phoneNumber: "(+34) 912 34 56 78",
    userRole: "Admin",
    status: "Active",
  },
  {
    id: "2",
    fullName: "Carlos López Martínez",
    avatar: "C",
    email: "carlos.lopez@crocante.com",
    phoneNumber: "(+34) 913 45 67 89",
    userRole: "Manager",
    status: "Registered",
  },
  {
    id: "3",
    fullName: "Elena Fernández Silva",
    avatar: "E",
    email: "elena.fernandez@crocante.com",
    phoneNumber: "(+34) 914 56 78 90",
    userRole: "User",
    status: "Active",
  },
  {
    id: "4",
    fullName: "Diego Moreno Ruiz",
    avatar: "D",
    email: "diego.moreno@crocante.com",
    phoneNumber: "(+34) 915 67 89 01",
    userRole: "Admin",
    status: "Active",
  },
  {
    id: "5",
    fullName: "Sofía Jiménez Gómez",
    avatar: "S",
    email: "sofia.jimenez@crocante.com",
    phoneNumber: "(+34) 916 78 90 12",
    userRole: "User",
    status: "Active",
  },
  {
    id: "6",
    fullName: "Javier Sánchez Pérez",
    avatar: "J",
    email: "javier.sanchez@crocante.com",
    phoneNumber: "(+34) 917 89 01 23",
    userRole: "Manager",
    status: "Invited",
  },
  {
    id: "7",
    fullName: "Laura Domínguez López",
    avatar: "L",
    email: "laura.dominguez@crocante.com",
    phoneNumber: "(+34) 918 90 12 34",
    userRole: "Admin",
    status: "Active",
  },
  {
    id: "8",
    fullName: "Roberto Vázquez Torres",
    avatar: "R",
    email: "roberto.vazquez@crocante.com",
    phoneNumber: "(+34) 919 01 23 45",
    userRole: "User",
    status: "Disabled",
  },
  {
    id: "9",
    fullName: "Natalia Ortiz Castillo",
    avatar: "N",
    email: "natalia.ortiz@crocante.com",
    phoneNumber: "(+34) 920 12 34 56",
    userRole: "Admin",
    status: "Active",
  },
  {
    id: "10",
    fullName: "Pablo Ramírez Alonso",
    avatar: "P",
    email: "pablo.ramirez@crocante.com",
    phoneNumber: "(+34) 921 23 45 67",
    userRole: "User",
    status: "Active",
  },
];
